services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./munchkin/staticfiles:/var/static/
      - /etc/letsencrypt/live/munchkin.site/privkey.pem:/etc/nginx/ssl/privkey.pem
      - /etc/letsencrypt/live/munchkin.site/fullchain.pem:/etc/nginx/ssl/fullchain.pem
    depends_on:
      - munchkin
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  munchkin:
    image: zothbwf/munchkin:latest
    container_name: munchkin
    command: ["daphne", "munchkin.asgi:application", "-b", "0.0.0.0","-p","8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
  static: