# Generated by Django 5.2.3 on 2025-06-25 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_hash", models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=20)),
                ("player_lvl", models.IntegerField(default=1)),
                ("player_equipment", models.IntegerField(default=0)),
                ("player_hash", models.CharField(max_length=20)),
                (
                    "player_game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["player_hash"], name="game_player_player__fcd9a5_idx"
                    )
                ],
            },
        ),
    ]
