# Generated by Django 5.2.3 on 2025-06-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="creation_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
