# Generated by Django 5.2.3 on 2025-06-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_player_creation_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="player_is_male",
            field=models.BooleanField(default=True),
        ),
    ]
