# Generated by Django 5.2.3 on 2025-06-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_player_player_is_male"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="player_is_male",
        ),
    ]
