# Generated by Django 5.2.3 on 2025-06-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_player_player_is_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1),
        ),
    ]
