# Generated by Django 5.2.3 on 2025-07-01 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_player_player_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="update_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="player",
            name="creation_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
