# Generated by Django 5.2.3 on 2025-07-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_creation_time_game_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
