# Generated by Django 5.2.4 on 2025-07-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_alter_game_update_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
